name: geocat_f2py_build
channels:
  - conda-forge
  - ncar
dependencies:
  - python
  - numpy=1.19
  - xarray
  - dask
  - pytest  # for tests
  - pytest-cov  # for tests
  - gfortran_linux-64
  - liblapack
  - pip:
      - pre-commit
