name: geocat_f2py_build
channels:
  - conda-forge
  - ncar
dependencies:
  - python
  - dask
  - gfortran_osx-64
  - numpy>=1.20.2
  - pip
  - pytest  # for tests
  - pytest-cov  # for tests
  - xarray
  - pip:
      - pre-commit
