package:
  name: "geocat-temp"
  version: "0.1"

source:
  git_rev: master
  git_url: https://github.com/NCAR/geocat-temp.git

requirements:
  host:
    - python=3.8
    - pip

  build:
    - python=3.8
    - numpy=1.19
    - gfortran_osx-64
    - lapack

  run:
    - python=3.8
    - dask
    - xarray
    - numpy=1.19
    - gfortran_osx-64
    - lapack

about:
  home: https://github.com/NCAR/geocat-temp
