package:
  name: 'geocat-f2py'
  version: '2021.02.0'

source:
  git_rev: main
  git_url: https://github.com/NCAR/geocat-f2py.git

build:
  number: 0
  skip: True # [py<35]

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy=1.19
    - {{ compiler('fortran') }}
  run:
    - python
    - xarray
    - dask
    - numpy=1.19
    - {{ compiler('fortran') }}

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - geocat.f2py
  commands:
    - pytest test

about:
  home: https://github.com/NCAR/geocat-f2py
