package:
  name: "geocat-temp"
  version: "0.2"

source:
  git_rev: master
  git_url: https://github.com/NCAR/geocat-temp.git

build:
  number: 1
  skip: True # [py<35]

requirements:
  build:
    - python
    - numpy
    - gfortran_osx-64
    - lapack
    - xarray
    - dask

  run:
    - python
    - numpy
    - gfortran_osx-64
    - lapack
    - xarray
    - dask

#test:
#  source_files:
#    - test
#  requires:
#    - pytest
#  imports:
#    - geocat.temp
#  commands:
#    - pytest test

about:
  home: https://github.com/NCAR/geocat-temp
