package:
  name: "geocat-f2py"
  version: "0.2.2"

source:
  git_rev: master
  git_url: https://github.com/NCAR/geocat-f2py.git

build:
  number: 2
  skip: True # [py<35]

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy=1.19
    - {{ compiler('fortran') }}
    - liblapack
    - xarray
    - dask
  run:
    - python
    - numpy=1.19
    - {{ compiler('fortran') }}
    - liblapack
    - xarray
    - dask

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - geocat.f2py
  commands:
    - pytest test

about:
  home: https://github.com/NCAR/geocat-f2py
