{% set name = "geocat-temp" %}
{% set version = "7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: latest
  git_url: https://github.com/NCAR/geocat-temp.git

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - dask
    - xarray
    - numpy


about:
  home: https://github.com/NCAR/geocat-temp
