package:
  name: "geocat-temp"
  version: "0.2"

source:
  git_rev: master
  git_url: https://github.com/NCAR/geocat-temp.git

build:
  number: 3
  skip: True # [py<35]

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy=1.19
    - {{ compiler('fortran') }}
    - libapack
    - xarray
    - dask
  run:
    - python
    - numpy=1.19
    - {{ compiler('fortran') }}
    - liblapack
    - xarray
    - dask

#test:
#  source_files:
#    - test
#  requires:
#    - pytest
#  imports:
#    - geocat.temp
#  commands:
#    - pytest test

about:
  home: https://github.com/NCAR/geocat-temp
