name: yapf
on: push
jobs:
  yapf_formatting:
    if: "contains(github.event.head_commit.message, 'trigger_yapf')"
    name: yapf_formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.A_KOOTZ_GEOCAT_F2PY_TOKEN }}
      - name: yapf
        run: |
          pip3 install yapf
          python3 -m yapf --in-place --recursive --style google .
      - name: push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@github.com'
          git commit --allow-empty -am "complete_yapf, trigger_build_test"
          git push